name: Deploying Lambda Function
on:
  push:
    branches:
      - main
env:
  PYTHON_VERSION: '3.11'  # Specify the Python version you want to use

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create dependencies directory
        run: mkdir -p dependencies

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t dependencies

      - name: Zip Dependencies
        run: zip -j lambda_deployment.zip ./dependencies

      - name: And Lambda Function Code to Zip
        run: zip -j lambda_deployment.zip ./lambda-function.py

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Update Lambda Function
        run: aws lambda update-function-code --function-name=catalyst_ngd_wrappers --zip-file=fileb://lambda_deployment.zip