name: Deploying Lambda Function
on:
  push:
    branches:
      - main
jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify your desired Python version
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - run: zip -j lambda.zip ./lambda/index.py  # Adjust the file path and name as needed
      - run: aws lambda update-function-code --function-name=my_lambda_function --zip-file=fileb://lambda.zip